name: Unit Tests

on:
  push:
    branches:
    - ci

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies and setup build directory
      run: |
        sudo apt install -y ninja-build
        mkdir build
       
    - name: CMake and Ninja
      run: |
        cmake -GNinja -DBUILD_TESTS=ON ..
        ninja
      working-directory: build

    - name: Ctest
      run: ctest
      working-directory: build