name: Unit Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      run: |
        sudo apt update
        sudo apt install clang-tidy-10
        mkdir build

    - name: Build Debug
      run: |
        cmake ..
        make -j`nproc`
      working-directory: build

    - name: Test Debug
      run: ctest --output-on-failure
      working-directory: build

    - name: Build Release+ASAN
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DLIBEDG_ASAN=ON ..
        make -j`nproc`
      working-directory: build

    - name: Test Release+ASAN
      run: ctest --output-on-failure
      working-directory: build
